#!/usr/bin/env node
// Reads the monorepo's canonical SKILL.md (single source of truth at the repo root)
// and emits src/skill-text.generated.ts — a plain TS string module imported by the
// worker (get_guide tool + learn prompt) and by the tests.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url)); // <repo>/mcp/scripts
const src = process.argv[2] || join(here, "../../SKILL.md"); // <repo>/SKILL.md

const md = readFileSync(src, "utf8");
const generated =
  "// AUTO-GENERATED by scripts/sync-skill.mjs — do not edit by hand.\n" +
  `export const SKILL_TEXT = ${JSON.stringify(md)};\n`;
writeFileSync(join(here, "../src/skill-text.generated.ts"), generated);
console.log(`Synced SKILL.md (${md.length} chars) from ${src}`);
